server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: incomes-ms
          uri: ${base-uri-incomes}
          predicates:
            - Path=/${apiVersion}/incomes/**
        - id: outcomes-ms
          uri: ${base-uri-outcomes}
          predicates:
            - Path=/${apiVersion}/outcomes/**
        - id: balance-ms
          uri: ${base-uri-balance}
          predicates:
            - Path=/${apiVersion}/balance/**

# common variables for routes
base-uri-incomes: http://localhost:8081
base-uri-outcomes: http://localhost:8081
base-uri-balance: http://localhost:8082
apiVersion: api/v1