server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: customer-ms
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/customers/**
        - id: product-ms
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: order-ms
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/orders/**
